name: Build & Push Container
  
on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
jobs:
  build-push-image:
    if: github.event.pull_request.merged == true
    name: Build & Push Image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ghcr.io/wh0ami1893/kickstats:latest --tag ghcr.io/wh0ami1893/kickstats:${{ github.ref_name }}
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main
      - name: 'Login to GitHub Container Registry'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{github.actor}}
          password: ${{secrets.GITHUB_TOKEN}}
      - name: Push Image'
        run: |
              docker push ghcr.io/wh0ami1893/kickstats:latest
              docker push ghcr.io/wh0ami1893/kickstats:${{ github.ref_name }}
        

