on:
  pull_request:
    types:
      - closed

jobs:
  publish:
    if: github.event.pull_request.merged == true
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag kickstats:$(date +%s)
